# Generated by Django 4.0.4 on 2022-04-26 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='payment_statuc',
            new_name='payment_status',
        ),
    ]
